version: '3.1'

services:

  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    